
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

LOCK TABLES `categories` WRITE;
/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (1,'Food & Snacks','food','#FF6B6B','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (2,'Movies','movie','#EC4899','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (3,'Tea','coffee','#F59E0B','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (4,'Therapy','brain','#8B5CF6','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (5,'Uber','car','#4ECDC4','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (6,'Audible Subscription','headphones','#A78BFA','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (7,'Google One Subscription','google','#3B82F6','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (8,'Ride / Transport','car','#4ECDC4','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (9,'Bills & Utilities','receipt','#3B82F6','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (10,'Shopping','shopping','#A78BFA','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (11,'Healthcare','hospital','#10B981','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (12,'Education','school','#F59E0B','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (13,'Groceries','cart','#10B981','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (14,'Personal Care','sparkles','#8B5CF6','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (15,'Online Services','web','#3B82F6','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (16,'Gym & Fitness','dumbbell','#FF6B6B','spending',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (17,'Income','cash','#10B981','income',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (18,'Bonus','gift','#F59E0B','income',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (19,'Investment','trending-up','#3B82F6','income',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (20,'Uncategorized','help-circle','#000000','both',1);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (23,'Comic book ','chart-arc','#EC4899','spending',0);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (24,'Bank reduction','bank-transfer-in','#F59E0B','spending',0);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (26,'Research Expenses','receipt','#6366F1','spending',0);
INSERT INTO `categories` (`id`, `name`, `icon`, `color`, `cat_type`, `is_default`) VALUES (27,'Reimbursement (Food expense)','human-greeting','#F59E0B','income',0);
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

